-- V1__init.sql
-- Estrutura inicial do banco (somente tabelas, sem triggers/lógica)

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ==========================
-- Tabela de Roles
-- ==========================
CREATE TABLE roles (
    id BIGINT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,  
    description TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);


-- ==========================
-- Tabela de Cursos
-- ==========================
CREATE TABLE courses (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW()
);


-- ==========================
-- Tabela de Polos (campus físico)
-- ==========================
CREATE TABLE campuses (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    address TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);


-- ==========================
-- Tabela de Usuários
-- ==========================
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(512) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    course_id BIGINT REFERENCES courses(id),
    campus_id BIGINT REFERENCES campuses(id),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);


-- ==========================
-- Relação N:N entre usuários e roles
-- ==========================
CREATE TABLE user_roles (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    assigned_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (user_id, role_id)
);


-- ==========================
-- Tabela de Avaliações (janelas de prova)
-- ==========================
CREATE TABLE evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    code VARCHAR(100) NOT NULL,
    title VARCHAR(255),
    
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,

    daily_start_time TIME NOT NULL,
    daily_end_time TIME NOT NULL,

    slot_duration_minutes INT NOT NULL DEFAULT 70,
    slot_capacity INT NOT NULL DEFAULT 5,

    campus_id BIGINT REFERENCES campuses(id),

    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW()
);


-- ==========================
-- Tabela de Agendamentos
-- ==========================
CREATE TABLE bookings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    evaluation_id BIGINT NOT NULL REFERENCES evaluations(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    slot_start TIMESTAMP NOT NULL,
    slot_end TIMESTAMP NOT NULL,  

    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED', 

    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO roles (id, name, description) VALUES
(1, 'ROLE_ADMIN', 'Administrador do sistema'),
(2, 'ROLE_STUDENT', 'Estudante'),
(3, 'ROLE_POLO', 'Polo');

-- Cursos
INSERT INTO courses (id, name) VALUES
(1, 'Administração'),
(2 ,'Direito'),
(3, 'Enfermagem'),
(4, 'Engenharia Civil'),
(5, 'Engenharia de Software'),
(6, 'Sistemas de Informação'),
(7, 'Pedagogia');

-- Campi (polos)
INSERT INTO campuses (id, name, address) VALUES
(1, 'Teresópolis', 'Rua Principal, 123'),
(2, 'Petrópolis', 'Avenida Norte, 456'),
(3, 'Nova Friburgo', 'Rua das Flores, 789'),
(4, 'Valença', 'Rodovia BR-101, Km 25'),
(5, 'Rio de Janeiro', 'Estrada da Colina, 980');


-- ==========================
-- Índices úteis
-- ==========================
CREATE INDEX idx_users_course ON users(course_id);
CREATE INDEX idx_users_campus ON users(campus_id);

CREATE INDEX idx_evaluations_date ON evaluations(start_date, end_date);
CREATE INDEX idx_evaluations_campus ON evaluations(campus_id);

CREATE INDEX idx_bookings_eval_slot ON bookings(evaluation_id, slot_start);
CREATE INDEX idx_bookings_user ON bookings(user_id);
